[package]
name = "unumdb"
version = "0.0.1"
authors = ["Unum Network Technology Company, Limited"]
edition = "2018"

[dependencies]
sha2 = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.0"
url = "1.7"

[dependencies.redis]
git = "https://github.com/mitsuhiko/redis-rs.git"

