[package]
name = "unumdb"
version = "0.0.1"
authors = ["Unum Network Technology Company, Limited"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.0"
url = "1.7"
redis = "0.10.0"
bson = "0.13"
