[package]
name = "immuxdb_client"
version = "0.1.0"
authors = ["Yiwang Network Technology Company, Limited"]
edition = "2018"

[dependencies]
reqwest = "0.9"
immuxdb = { path = "../../.." }

[lib]
name = "immuxdb_client"
path = "client.rs"
